name: Build and publish Windows artifact

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore and publish C# project
        run: |
          dotnet restore serialCodigo.csproj
          dotnet publish serialCodigo.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o publish/csharp

      - name: Upload C# artifact
        uses: actions/upload-artifact@v4
        with:
          name: serialCodigo-csharp-win-x64
          path: publish/csharp/
